#!/bin/bash

set -ex

CPU=${1:-cortex-m33}
DEBUG=${2:-no}

#same as buildit-mlkem-small, with wolfSSL's Thumb-2 assembly (cortex-m* only), installed in build/$CPU-small-armasm
ARMASM=yes ./buildit-mlkem-small $CPU $DEBUG
