#!/bin/bash

set -ex

CPU=${1:-cortex-m33}
GOAL=${2:-fast}
DEBUG=${3:-no}

source ./buildit-toolchain

BUILDDIR=`pwd`/build/$CPU-$GOAL
./autogen.sh
./configure \
  --enable-debug=$DEBUG \
  --host=$TOOLCHAIN \
  CC=$TOOLCHAIN-gcc \
  AR=$TOOLCHAIN-gcc-ar \
  STRIP=$TOOLCHAIN-strip \
  RANLIB=$TOOLCHAIN-gcc-ranlib \
  --prefix=$BUILDDIR \
  CFLAGS="$CPU_FLAGS --specs=nosys.specs -flto -ffat-lto-objects \
      -DHAVE_PK_CALLBACKS -DWOLFSSL_USER_IO -DWOLFSSL_NO_SOCK -DWC_NO_RNG -DNO_WRITEV -DNO_WOLFSSL_DIR -DWOLFSSL_DILITHIUM_NO_ASN1 ${*:4}" \
  --disable-filesystem --disable-crypttests \
  --disable-shared --enable-cryptonly --enable-mldsa \
  --enable-mlkem=yes\
  --enable-dh=no\
  --enable-ecc=no\
  --enable-aes=yes --enable-aesgcm=yes\
  --enable-chacha=yes\
  --enable-pkcs8=no\
  --enable-pkcs12=no\
  --enable-tls=no\
  --enable-tlsv12=no\
  --enable-tls13=no\
  --enable-asn=no\
  --enable-rsa=no\
  --enable-hkdf=yes\
  --enable-pwdbased=no\
  --enable-hashdrbg=yes\
  --enable-sha=yes\
  --enable-aescbc=yes\
  --enable-harden=yes #keep it enabled as it just mean timing resistance

make
make install
